[".bash-preexec.sh"]
type = "file"
url = "https://raw.githubusercontent.com/rcaloras/bash-preexec/master/bash-preexec.sh"
refreshPeriod = "168h"

["~/.config/alacritty/catppuccin-latte.toml"]
type = "file"
url = "https://github.com/catppuccin/alacritty/raw/main/catppuccin-latte.toml"
refreshPeriod = "168h"

["~/.config/alacritty/catppuccin-frappe.toml"]
type = "file"
url = "https://github.com/catppuccin/alacritty/raw/main/catppuccin-frappe.toml"
refreshPeriod = "168h"

["~/.config/alacritty/catppuccin-macchiato.toml"]
type = "file"
url = "https://github.com/catppuccin/alacritty/raw/main/catppuccin-macchiato.toml"
refreshPeriod = "168h"

["~/.config/alacritty/catppuccin-mocha.toml"]
type = "file"
url = "https://github.com/catppuccin/alacritty/raw/main/catppuccin-mocha.toml"
refreshPeriod = "168h"
