name: Test
on:
  push:
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - name: Set up chezmoi
        run: 'sh -c "$(curl -fsLS get.chezmoi.io)" -- init -S . --no-tty --promptDefaults --apply'
        shell: bash
